In [3]:
import numpy as np
import sympy as sp
import numpy.linalg as la

In [4]:
vector0 = np.array([2,4,5], dtype=np.int64)
vector1 = np.array([4,2,8], dtype=np.int64)
old_vectors = [vector0, vector1]
new_vector = np.array([6,9,14], dtype=np.int64) # 2*vector1 + .5*vector2

In [5]:
sp.Matrix(vector1)

Matrix([
[4],
[2],
[8]])

In [6]:
np.array([vector0, vector1, vector1])

array([[2, 4, 5],
       [4, 2, 8],
       [4, 2, 8]])

In [7]:
for count, value in enumerate(sp.Matrix(vector1)):
    print(count, value)

0 4
1 2
2 8


In [8]:
sp.Matrix([vector1[2], vector2[2]])

NameError: name 'vector2' is not defined

In [9]:
len(sp.Matrix(vector1))

3

In [10]:
vector1 = sp.Matrix(vector1)
vector2 = sp.Matrix(vector2)
sp.Matrix([vector1.T,vector2.T]).T

NameError: name 'vector2' is not defined

In [11]:
sp.Matrix([vector1.T,vector2.T]).T[:,0]

NameError: name 'vector2' is not defined

In [12]:
import lattice
import lattice_new
from importlib import reload  


In [13]:
lattice_new = reload(lattice_new)
lattice = reload(lattice)
solution_new = lattice_new.reduce_spanning_set_3d(old_vectors, new_vector)
solution_old = lattice.reduce_spanning_set_3d(old_vectors, new_vector)
sp.pprint(solution_new)
sp.pprint(solution_old)

[[2 4 5], [ 6  9 14]]
[[2 4 5], [ 6  9 14]]


In [14]:
type(solution_new[1])

numpy.ndarray

In [15]:
type(solution_new[0][1])

numpy.int32

In [36]:
a = -10
b = 10
def linearly_independent(vectors):
    if len(vectors) == 0:
        result = True
    elif len(vectors) == 1:
        result = (la.norm(vectors[0]) > .1)
    elif len(vectors) == 2:
        product = np.cross(vectors[0], vectors[1])
        result = (la.norm(product) > .1)
    elif len(vectors) == 3:
        result = (la.det(np.array(vectors)) > .1)
    else:
        raise ValueError("Input basis too large")
    return result

def generate_basis(size):
    vectors = []
    for i in range(size):
        vector = np.array(np.random.randint(a,b,(3)),dtype=np.int32)
        vectors.append(vector)
    while not linearly_independent(vectors):
        vectors = generate_basis(size)
    return vectors

def trivial_case():
    base_size = np.random.randint(0,3)
    old_vectors = generate_basis(base_size)
    new_vector = np.zeros(3, dtype=np.int32)
    return old_vectors, new_vector

def case1a():
    # in some cases could be trivial
    base_size = 1
    old_vectors = generate_basis(base_size)
    new_vector = np.random.randint(-5,5)*old_vectors[0]
    return old_vectors, new_vector

def case1b():
    # in some cases could be 1a
    base_size = 1
    old_vectors = generate_basis(base_size)
    new_vector = np.random.randint(a,b,3).astype(np.int32)
    return old_vectors, new_vector

def case2a():
    # in some cases could be trivial
    base_size = 2
    old_vectors = generate_basis(base_size)
    new_vector = np.random.randint(-5,5)*old_vectors[0] + np.random.randint(-5,5)*old_vectors[1] 
    return old_vectors, new_vector

def case2b():
    # in some cases could be trivial
    base_size = 2
    old_vectors = generate_basis(base_size)
    new_vector = np.random.randint(a,b,3).astype(np.int32)
    return old_vectors, new_vector

def case3():
    base_size = 3
    old_vectors = generate_basis(base_size)
    new_vector = np.random.randint(a,b,3).astype(np.int32)
    return old_vectors, new_vector
    
def test_case(case):
    old_vectors, new_vector = case()
    try:
        solution_new = lattice_new.reduce_spanning_set_3d(old_vectors, new_vector)
    except Exception as e:
        print(old_vectors, new_vector)
        print(e)
        return
    solution_old = lattice.reduce_spanning_set_3d(old_vectors, new_vector)
    #sp.pprint(solution_new)
    #sp.pprint(solution_old)
    error = 0
    for vector1, vector2 in zip(*[solution_new, solution_old]):
        difference = (vector1-vector2).astype(float)
        error += la.norm(difference)
    if error > 1e-6:
        print(f"input vectors:\n{old_vectors}\n{new_vector}\n")
        print(f"resulting spanning set old:\n{solution_old}\n")
        print(f"resulting spanning set new:\n{solution_new}\n")
        print(f"vectors in question:\n{vector1} vs {vector2}")
        print(f"error = {error}")
        raise ValueError("Vectors don't match")
    
    

In [37]:
lattice_new = reload(lattice_new)
lattice = reload(lattice)
old_vectors, new_vector = case3()
lattice_new.reduce_spanning_set_3d(old_vectors, new_vector)

[array([-532, -444,  214], dtype=int32),
 array([1, 3, 6], dtype=int32),
 array([-10,  -7,   8], dtype=int32)]

In [38]:
lattice_new = reload(lattice_new)
lattice = reload(lattice)
for i in range(10000):
    test_case(trivial_case)
    test_case(case1a)
    test_case(case1b)
    test_case(case2a)
    test_case(case2b)
    test_case(case3)

In [32]:
lattice_new = reload(lattice_new)
lattice = reload(lattice)
old_vectors = [np.array([-9, -9, -9], dtype=np.int32), np.array([ 7, -6, -3], dtype=np.int32), np.array([-6, -4, -2], dtype=np.int32)]
new_vector = np.array([-10, -10, -10], dtype=np.int32)
print(lattice.reduce_spanning_set_3d(old_vectors, new_vector))
print()
print(lattice_new.reduce_spanning_set_3d(old_vectors, new_vector))

abc
[array([ 7, -6, -3], dtype=int32), array([-6, -4, -2], dtype=int32), array([-1, -1, -1], dtype=int32)]

[array([ 7, -6, -3], dtype=int32), array([-6, -4, -2], dtype=int32), array([-1, -1, -1], dtype=int32)]
